version: "3.7"

services:
  mysql_strapi:
    image: mysql:latest
    container_name: mysql_next_strapi_blog
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
    ports:
      - "3306:3306"
    volumes:
      - strapi_data:/var/lib/mysql
    networks:
      - network_strapi

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: strapi_phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: mysql_strapi
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql_strapi
    networks:
      - network_strapi

volumes:
  strapi_data:
    driver: local

networks:
  network_strapi:
    driver: bridge